import { describe, expect, it } from 'vitest';
import { PDFArray, PDFDict, PDFDocument, PDFName, PDFString } from 'pdf-lib';

import { composeReportSheet } from '../report-sheet';
import { buildProjectReportSheet, projectBanner } from '@/lib/domain/project-report-sheet';
import type { ReportContent } from '@/lib/domain/report-content';

/* ============================================================================
 * THE PROJECT REPORT ON THE REPORTS-PAGE SHEET — owner, 2026-09-03
 * ----------------------------------------------------------------------------
 * *"I want this template of the PDF that I have here with you as a screenshot.
 * It's the same template which is in the /report page… each task is mentioned
 * separately, who did it, what their status is, and which platforms have been
 * done."*
 *
 * ⚠️ AND THE LINKS HAD TO SURVIVE THE MOVE. They were asked for one message
 * earlier, and this renderer's generic table draws TEXT — so switching to it
 * without `linkColumn` would have silently undone them. That is the case this
 * file exists to hold.
 * ========================================================================= */

const content = (over: Partial<ReportContent> = {}): ReportContent => ({
  kind: 'today',
  projectName: 'Test Project 2',
  projectCode: 'CLI',
  periodLabel: '3 September 2026',
  kindLabel: 'DAILY REPORT',
  introduction: ['An external client engagement on the STARTER package.'],
  headline: [
    { label: 'TARGET FOR THIS PERIOD', value: '2', sub: 'from the agreed rhythm' },
    { label: 'ACHIEVED', value: '2', sub: '1 static - 1 reel' },
    { label: 'REMAINING', value: '0', sub: '100% of the target met' },
  ],
  platforms: ['Facebook', 'Instagram', 'TikTok'],
  rows: [],
  published: [
    {
      task: 'Eid sale post',
      reference: 'CLI-1568',
      contentType: 'Static Post',
      person: 'Abdul Moiz',
      status: 'Done',
      platform: 'Facebook, Instagram',
      platformSlugs: ['facebook', 'instagram'],
      time: '',
      url: 'https://facebook.com/story.php?story_fbid=123',
    },
    {
      task: 'Behind the scenes reel',
      reference: 'CLI-1569',
      contentType: 'Reel',
      person: 'Kashif',
      status: 'In Review',
      platform: 'TikTok',
      platformSlugs: ['tiktok'],
      time: '',
      url: '',
    },
  ],
  people: [{ name: 'Abdul Moiz', posts: 1, done: 1 }],
  platformSummaries: [],
  glance: ['All targets achieved.'],
  notes: [],
  activityTotal: '2',
  activityCaption: '1 static post and 1 reel were published today.',
  footer: 'Generated by Taskly.',
  ...over,
});

const PERIOD = { start: '2026-09-03', end: '2026-09-03' };
const META = { generatedOn: '2026-09-03', generatedBy: 'Umm-e-Habiba' };

const urisIn = async (pdf: Uint8Array): Promise<string[]> => {
  const doc = await PDFDocument.load(pdf);
  const found: string[] = [];
  for (const page of doc.getPages()) {
    const annots = page.node.lookupMaybe(PDFName.of('Annots'), PDFArray);
    if (!annots) continue;
    for (let i = 0; i < annots.size(); i += 1) {
      const uri = annots
        .lookup(i, PDFDict)
        .lookupMaybe(PDFName.of('A'), PDFDict)
        ?.lookupMaybe(PDFName.of('URI'), PDFString);
      if (uri) found.push(uri.asString());
    }
  }
  return found;
};

describe('buildProjectReportSheet', () => {
  it('makes one row per task, with who did it and its status', () => {
    const report = buildProjectReportSheet(content(), PERIOD);

    expect(report.rows).toHaveLength(2);
    expect(report.columns.map((c) => c.label)).toEqual([
      'Task',
      'Reference',
      'Category',
      'Who did it',
      'Platforms',
      'Status',
      'Live link',
    ]);
    expect(report.rows[0].map((cell) => cell.value)).toEqual([
      'Eid sale post',
      'CLI-1568',
      'Static Post',
      'Abdul Moiz',
      'Facebook, Instagram',
      'Done',
      'facebook.com/story.php?story_fbid=123',
    ]);
  });

  it('names the project and the period in the subtitle', () => {
    const report = buildProjectReportSheet(content(), PERIOD);
    expect(report.subtitle).toContain('Test Project 2');
    expect(report.subtitle).toContain('3 September 2026');
  });

  /* ⚠️ `content.headline` holds STRINGS. `Number('5 of 7')` is NaN, which would
     print "NaN" on a client's document. */
  it('reads a number out of a headline value without producing NaN', () => {
    const report = buildProjectReportSheet(
      content({
        headline: [{ label: 'ACHIEVED', value: '5 of 7', sub: '' }],
      }),
      PERIOD,
    );
    expect(report.figures[0].value.value).toBe(5);
  });

  it('names who did the work in the notes', () => {
    const report = buildProjectReportSheet(content(), PERIOD);
    expect(report.notes.some((note) => note.includes('Abdul Moiz'))).toBe(true);
  });

  it('shows a dash rather than an empty cell for a post with no link', () => {
    const report = buildProjectReportSheet(content(), PERIOD);
    expect(report.rows[1][6].value).toBe('-');
  });
});

describe('the sheet keeps the links clickable', () => {
  const build = () =>
    composeReportSheet({
      report: buildProjectReportSheet(content(), PERIOD),
      work: null,
      charts: [],
      filterSummary: ['Project: Test Project 2'],
      ...META,
      linkColumn: {
        index: 6,
        hrefs: content().published.map((row) => row.url || null),
      },
    });

  it('writes an annotation carrying the FULL address', async () => {
    const uris = await urisIn(await build());
    /* The cell shows it without the scheme; the link must still resolve. */
    expect(uris).toContain('https://facebook.com/story.php?story_fbid=123');
  });

  it('writes no annotation for the row that has no link', async () => {
    expect(await urisIn(await build())).toHaveLength(1);
  });
});

/* ============================================================================
 * THE SUMMARY, AND WHAT IT MUST NOT DO — owner, 2026-09-03
 * ----------------------------------------------------------------------------
 * *"you are repeating the same thing again and again. Give a proper report or
 * you can say a summary… some tips."*
 * ========================================================================= */
describe('the notes block', () => {
  /* ⚠️ The promise itself lives in the BANNER, above the figure cards. The notes
     open with the comparison against it, not with a second copy of it. */
  it('opens with what the period asked for and what came of it', () => {
    const report = buildProjectReportSheet(content(), PERIOD);
    expect(report.notes[0]).toContain('asked for 2');
    expect(report.notes[0]).toContain('2 went out');
  });

  /* ⚠️ THE REGRESSION THIS EXISTS FOR. The first version poured in glance AND
     people AND notes, and the per-person lines were already in glance — so
     every name appeared twice in slightly different words. */
  it('names each person at most once', () => {
    const report = buildProjectReportSheet(content(), PERIOD);
    const mentions = report.notes.filter((note) => note.includes('Abdul Moiz')).length;
    expect(mentions).toBeLessThanOrEqual(1);
  });

  it('does not repeat the figure cards as prose', () => {
    const report = buildProjectReportSheet(content(), PERIOD);
    /* "All targets achieved." is a glance line and a figure card. It must not
       also be a note. */
    expect(report.notes).not.toContain('All targets achieved.');
  });

  /* Advice appears only where a figure asks for it. */
  it('offers a tip about missing links when one is missing', () => {
    const report = buildProjectReportSheet(content(), PERIOD);
    expect(report.notes.some((note) => note.includes('no live link recorded'))).toBe(true);
  });

  it('offers no tips at all when nothing is outstanding', () => {
    const clean = content({
      headline: [
        { label: 'TARGET FOR THIS PERIOD', value: '1', sub: '' },
        { label: 'ACHIEVED', value: '1', sub: '' },
        { label: 'REMAINING', value: '0', sub: '' },
      ],
      published: [
        {
          task: 'Eid sale post',
          reference: 'CLI-1568',
          contentType: 'Static Post',
          person: 'Abdul Moiz',
          status: 'Done',
          platform: 'Facebook',
          platformSlugs: ['facebook'],
          time: '',
          url: 'https://facebook.com/p/1',
        },
      ],
    });

    const report = buildProjectReportSheet(clean, PERIOD);
    expect(report.notes.some((note) => note.includes('Nothing outstanding'))).toBe(true);
    expect(report.notes.some((note) => note.includes('no live link'))).toBe(false);
  });
});

describe('projectBanner', () => {
  it('carries the project name and the agreed rhythm', () => {
    const banner = projectBanner(content());
    expect(banner.title).toBe('Test Project 2');
    expect(banner.lines.join(' ')).toContain('STARTER package');
  });
});

/* ============================================================================
 * EVERY FINISHED TASK, NOT ONLY WHAT WENT OUT — owner, 2026-09-03
 * ----------------------------------------------------------------------------
 * *"Display all the done tasks for that project, not only static or real."*
 *
 * The table was built from the PACKAGE list — content, published, dated — and so
 * dropped CLI-1580: kind `other`, finished on the day, never published. Real
 * work, invisible.
 * ========================================================================= */
describe('ordinary work appears too', () => {
  const mixed = () =>
    content({
      published: [
        {
          task: '1st static Test',
          reference: 'CLI-1574',
          contentType: 'Static post',
          person: 'Kashif',
          status: 'Done',
          platform: 'Facebook, Instagram, TikTok',
          platformSlugs: ['facebook', 'instagram', 'tiktok'],
          time: '',
          url: 'https://facebook.com/p/1',
        },
        {
          /* ⚠️ THE ROW THAT WAS MISSING. No content kind, no platforms, no link
             — and still a finished piece of work somebody did that day. */
          task: 'other Tasks',
          reference: 'CLI-1580',
          contentType: 'Task',
          person: 'Abdul Moiz',
          status: 'Done',
          platform: '—',
          platformSlugs: [],
          time: '',
          url: '',
        },
      ],
    });

  it('lists work with no content kind, categorised as a Task', () => {
    const report = buildProjectReportSheet(mixed(), PERIOD);

    expect(report.rows).toHaveLength(2);
    expect(report.rows[1][0].value).toBe('other Tasks');
    /* Named, not blank: the owner asked for the category to say whether a row is
       a task or a static post. */
    expect(report.rows[1][2].value).toBe('Task');
  });

  it('shows a dash for its platforms and its link rather than an empty cell', () => {
    const report = buildProjectReportSheet(mixed(), PERIOD);
    expect(report.rows[1][4].value).toBe('—');
    expect(report.rows[1][6].value).toBe('-');
  });

  it('counts it in Tasks listed', () => {
    const report = buildProjectReportSheet(mixed(), PERIOD);
    const listed = report.figures.find((f) => f.label === 'Tasks listed');
    expect(listed?.value.value).toBe(2);
  });

  /* ⚠️ It must NOT reach the target figures. The package counts published
     content; a finished internal task counting towards a client's promise would
     overstate delivery. */
  it('does not inflate the target figures', () => {
    const report = buildProjectReportSheet(mixed(), PERIOD);
    const achieved = report.figures.find((f) => f.label.includes('ACHIEVED'));
    expect(achieved?.value.value).toBe(2); // from content.headline, untouched
  });
});
