import { describe, expect, it } from 'vitest';
import { PDFArray, PDFDict, PDFDocument, PDFName, PDFString } from 'pdf-lib';

import { composeReportSheet } from '../report-sheet';
import { buildProjectReportSheet } from '@/lib/domain/project-report-sheet';
import type { ReportContent } from '@/lib/domain/report-content';

/* ============================================================================
 * THE PROJECT REPORT ON THE REPORTS-PAGE SHEET — owner, 2026-09-03
 * ----------------------------------------------------------------------------
 * *"I want this template of the PDF that I have here with you as a screenshot.
 * It's the same template which is in the /report page… each task is mentioned
 * separately, who did it, what their status is, and which platforms have been
 * done."*
 *
 * ⚠️ AND THE LINKS HAD TO SURVIVE THE MOVE. They were asked for one message
 * earlier, and this renderer's generic table draws TEXT — so switching to it
 * without `linkColumn` would have silently undone them. That is the case this
 * file exists to hold.
 * ========================================================================= */

const content = (over: Partial<ReportContent> = {}): ReportContent => ({
  kind: 'today',
  projectName: 'Test Project 2',
  projectCode: 'CLI',
  periodLabel: '3 September 2026',
  kindLabel: 'DAILY REPORT',
  introduction: ['An external client engagement on the STARTER package.'],
  headline: [
    { label: 'TARGET FOR THIS PERIOD', value: '2', sub: 'from the agreed rhythm' },
    { label: 'ACHIEVED', value: '2', sub: '1 static - 1 reel' },
    { label: 'REMAINING', value: '0', sub: '100% of the target met' },
  ],
  platforms: ['Facebook', 'Instagram', 'TikTok'],
  rows: [],
  published: [
    {
      task: 'Eid sale post',
      reference: 'CLI-1568',
      contentType: 'Static Post',
      person: 'Abdul Moiz',
      status: 'Done',
      platform: 'Facebook, Instagram',
      time: '',
      url: 'https://facebook.com/story.php?story_fbid=123',
    },
    {
      task: 'Behind the scenes reel',
      reference: 'CLI-1569',
      contentType: 'Reel',
      person: 'Kashif',
      status: 'In Review',
      platform: 'TikTok',
      time: '',
      url: '',
    },
  ],
  people: [{ name: 'Abdul Moiz', posts: 1, done: 1 }],
  platformSummaries: [],
  glance: ['All targets achieved.'],
  notes: [],
  activityTotal: '2',
  activityCaption: '1 static post and 1 reel were published today.',
  footer: 'Generated by Taskly.',
  ...over,
});

const PERIOD = { start: '2026-09-03', end: '2026-09-03' };
const META = { generatedOn: '2026-09-03', generatedBy: 'Umm-e-Habiba' };

const urisIn = async (pdf: Uint8Array): Promise<string[]> => {
  const doc = await PDFDocument.load(pdf);
  const found: string[] = [];
  for (const page of doc.getPages()) {
    const annots = page.node.lookupMaybe(PDFName.of('Annots'), PDFArray);
    if (!annots) continue;
    for (let i = 0; i < annots.size(); i += 1) {
      const uri = annots
        .lookup(i, PDFDict)
        .lookupMaybe(PDFName.of('A'), PDFDict)
        ?.lookupMaybe(PDFName.of('URI'), PDFString);
      if (uri) found.push(uri.asString());
    }
  }
  return found;
};

describe('buildProjectReportSheet', () => {
  it('makes one row per task, with who did it and its status', () => {
    const report = buildProjectReportSheet(content(), PERIOD);

    expect(report.rows).toHaveLength(2);
    expect(report.columns.map((c) => c.label)).toEqual([
      'Task',
      'Reference',
      'Category',
      'Who did it',
      'Platforms',
      'Status',
      'Live link',
    ]);
    expect(report.rows[0].map((cell) => cell.value)).toEqual([
      'Eid sale post',
      'CLI-1568',
      'Static Post',
      'Abdul Moiz',
      'Facebook, Instagram',
      'Done',
      'facebook.com/story.php?story_fbid=123',
    ]);
  });

  it('names the project and the period in the subtitle', () => {
    const report = buildProjectReportSheet(content(), PERIOD);
    expect(report.subtitle).toContain('Test Project 2');
    expect(report.subtitle).toContain('3 September 2026');
  });

  /* ⚠️ `content.headline` holds STRINGS. `Number('5 of 7')` is NaN, which would
     print "NaN" on a client's document. */
  it('reads a number out of a headline value without producing NaN', () => {
    const report = buildProjectReportSheet(
      content({
        headline: [{ label: 'ACHIEVED', value: '5 of 7', sub: '' }],
      }),
      PERIOD,
    );
    expect(report.figures[0].value.value).toBe(5);
  });

  it('says what each person did in the notes', () => {
    const report = buildProjectReportSheet(content(), PERIOD);
    expect(report.notes.some((note) => note.includes('Abdul Moiz published 1 post'))).toBe(true);
  });

  it('shows a dash rather than an empty cell for a post with no link', () => {
    const report = buildProjectReportSheet(content(), PERIOD);
    expect(report.rows[1][6].value).toBe('-');
  });
});

describe('the sheet keeps the links clickable', () => {
  const build = () =>
    composeReportSheet({
      report: buildProjectReportSheet(content(), PERIOD),
      work: null,
      charts: [],
      filterSummary: ['Project: Test Project 2'],
      ...META,
      linkColumn: {
        index: 6,
        hrefs: content().published.map((row) => row.url || null),
      },
    });

  it('writes an annotation carrying the FULL address', async () => {
    const uris = await urisIn(await build());
    /* The cell shows it without the scheme; the link must still resolve. */
    expect(uris).toContain('https://facebook.com/story.php?story_fbid=123');
  });

  it('writes no annotation for the row that has no link', async () => {
    expect(await urisIn(await build())).toHaveLength(1);
  });
});
