import 'server-only';

import { APP_NAME, DIVISION_NAME, ORGANISATION_NAME, SYSTEM_DEFAULTS } from '@/lib/domain/constants';
import { maskEmail } from '@/lib/domain/email-address';
import {
  MARK_BASE64,
  MARK_CID,
  MARK_FILENAME,
  MARK_HEIGHT,
  MARK_WIDTH,
} from './mark';
import {
  INVITE_BADGE,
  KEY_BADGE,
  MAIL,
  NOTCH,
  ROLE,
  SHIELD_NOTE,
  SHIELD_RULE,
  type EmailIcon,
} from './icons';

/* ============================================================================
 * EMAIL TEMPLATES
 * ----------------------------------------------------------------------------
 * ── BUILT TO THE OWNER'S REFERENCE DESIGN, 2026-08-24 ────────────────────────
 * *"I want the exact icon, the size of the logo, and each and every thing you
 * can see. I want this same email template."*
 *
 * So this is a reconstruction of a supplied design rather than a set of choices
 * made here. Its structure, in order: a dark header band carrying the mark and
 * the wordmark; a gold rule with a small tab hanging off it; a ringed icon
 * badge; a centred headline over a short gold divider; the body; a gold-tinted
 * role chip; the action; a security note; a shield-centred divider; the
 * paste-this-instead link; and a pale footer band inside the card.
 *
 * ── EVERY ICON IS AN ATTACHED PNG, AND THAT IS NOT A SHORTCUT ────────────────
 * Gmail strips <svg> outright, so the lucide icons the application uses cannot
 * travel into a message. Emoji render as a different picture in every client.
 * So each glyph is a PNG generated by scripts/make-email-icons.mjs, attached to
 * the message and referenced with `cid:` — which needs no network fetch and is
 * therefore immune to the image blocking every major client does by default.
 * See ./icons.ts. Each template declares only the icons it actually uses, so a
 * password-reset message does not carry the invitation's badge.
 *
 * ── ALWAYS THE LIGHT PALETTE, NEVER THE DARK ONE (FR-215) ────────────────────
 * The application has a dark theme. Email does not get one. Dark-mode handling
 * in mail clients ranges from good to actively destructive — Outlook inverts
 * some colours and not others, several ignore `prefers-color-scheme`, and a few
 * rewrite backgrounds while leaving text alone. Unreadable in a way you cannot
 * test for. The dark header band is not an exception: it is painted explicitly
 * with BOTH a `bgcolor` attribute and a CSS background, which is how a colour
 * survives a client that strips one or the other.
 *
 * ── INLINE STYLES, TABLES, NO CSS VARIABLES ──────────────────────────────────
 * Everything the app does properly, email must do the 2005 way. `var()` is
 * unsupported in most clients, flexbox is unreliable, and `border-radius` is
 * ignored by Outlook's Word renderer — which is why the badge and the notch are
 * images rather than styled boxes. The hex values below are the only place in
 * this codebase where BR-025 is deliberately broken, because a token cannot
 * survive the journey into somebody's inbox.
 *
 * ── EVERY TEMPLATE RETURNS TEXT AS WELL ──────────────────────────────────────
 * Not politeness. A message with no plain-text alternative scores worse with
 * spam filters, and ADR-007's recovery design assumes these arrive.
 * ========================================================================= */

/* ── THE PALETTE ──────────────────────────────────────────────────────────────
   Read off the reference design and reconciled with styles/tokens.css, which is
   why each constant names its token where one exists.

   ⚠️ GOLD IS NOT A TEXT COLOUR ON WHITE — tokens.css measures gold-500 on white
   at 2.1:1. So gold appears here ONLY as a rule, a border, a chip background and
   an icon stroke; no text anywhere below is set in it. The one gold that is safe
   on light is gold-800 (5.4:1), and it lives in scripts/make-email-icons.mjs as
   the stroke colour for the glyphs that sit on the tinted panels. */
const BAND = '#0e2a2c'; /* ⚠️ must match BAND in scripts/make-email-mark.mjs */
const BAND_HEADING = '#ffffff';
const BAND_MUTED = '#9fb6b8';
const BRAND = '#0e5c63'; /* --teal-700, core brand teal */
const BRAND_DEEP = '#0a4046'; /* --teal-800 */
const GOLD = '#d4a63c'; /* --gold-500 */
const CHIP_BG = '#f8edd9'; /* --gold-100 */
const CHIP_EDGE = '#f2ddb4'; /* --gold-200 */
const INK = '#12222a'; /* --text-primary */
const BODY = '#3f5157';
const MUTED = '#5b6f77'; /* --text-secondary */
const BORDER = '#dde7e8'; /* --neutral-200 */
const HAIRLINE = '#e6eded';
const PANEL = '#f4f8f8'; /* --neutral-50 */
const PAGE = '#eef3f3';
const FOOT_BG = '#eef3f3';
const LINK = '#1155cc'; /* what a mail client renders a link as anyway */

const SANS = '-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica,Arial,sans-serif';
const MONO = 'ui-monospace,SFMono-Regular,Menlo,Consolas,monospace';

export interface EmailAttachment {
  readonly filename: string;
  readonly content: string;
  readonly contentId: string;
  readonly contentType: string;
}

export interface Email {
  readonly subject: string;
  readonly html: string;
  readonly text: string;
  /** Inline images, by content id. Never empty — the mark is on every message. */
  readonly attachments: readonly EmailAttachment[];
}

/* --------------------------------------------------------------------------
 * Attachments
 * ------------------------------------------------------------------------ */

const MARK_ATTACHMENT: EmailAttachment = {
  filename: MARK_FILENAME,
  content: MARK_BASE64,
  contentId: MARK_CID,
  contentType: 'image/png',
};

const asAttachment = (icon: EmailIcon): EmailAttachment => ({
  filename: icon.filename,
  content: icon.base64,
  contentId: icon.cid,
  contentType: 'image/png',
});

/** The mark and the notch are on every message; the rest are per-template. */
const attach = (...icons: EmailIcon[]): EmailAttachment[] => [
  MARK_ATTACHMENT,
  asAttachment(NOTCH),
  ...icons.map(asAttachment),
];

const img = (icon: EmailIcon, alt = ''): string =>
  `<img src="cid:${icon.cid}" width="${icon.width}" height="${icon.height}" alt="${alt}"
        style="display:block;width:${icon.width}px;height:${icon.height}px;border:0;outline:none;text-decoration:none;" />`;

/* --------------------------------------------------------------------------
 * The shell
 * ------------------------------------------------------------------------ */

/**
 * The frame every message shares.
 *
 * ⚠️ No `appUrl` parameter. It existed only to build an absolute URL for the
 * header image; the image is attached now, so there is nothing left for a
 * caller to get wrong.
 */
function shell(body: string, preheader: string): string {
  return `<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${APP_NAME}</title></head>
<body style="margin:0;padding:0;background:${PAGE};-webkit-font-smoothing:antialiased;">
  <!-- The inbox preview line. Hidden in the body, but it is the first thing
       anybody reads, so it says something useful rather than repeating the
       subject. The zero-width run after it stops Gmail pulling the opening
       sentence in behind it. -->
  <div style="display:none;max-height:0;overflow:hidden;opacity:0;">${preheader}</div>
  <div style="display:none;max-height:0;overflow:hidden;">&#8203;&#8203;&#8203;&#8203;&#8203;&#8203;&#8203;&#8203;&#8203;&#8203;</div>

  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background:${PAGE};padding:32px 12px;">
    <tr><td align="center">
      <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="max-width:620px;background:#ffffff;border:1px solid ${BORDER};border-radius:10px;overflow:hidden;">

        <!-- ── THE HEADER BAND ────────────────────────────────────────────────
             ⚠️ THE MARK IS AN IMAGE WITH REAL TEXT BESIDE IT, NOT INSTEAD OF
             IT. The image is attached rather than remote so it is not blocked
             the way a tracking pixel is — but a client can still fail to render
             it, and the product name must never depend on a picture. The
             wordmark is text; the mark is the flourish.
             ⚠️ NO BACKTICKS IN THIS COMMENT. It sits inside a JS template
             literal, so one would end the string and the file would stop
             parsing — which is exactly what happened when this was written.
             The alt is empty because the name is spelled out beside it; a
             screen reader announcing "Taskly logo Taskly" is noise. -->
        <tr><td bgcolor="${BAND}" style="background:${BAND};padding:22px 34px;">
          <table role="presentation" cellpadding="0" cellspacing="0" border="0"><tr>
            <td style="padding-right:14px;vertical-align:middle;">
              <img src="cid:${MARK_CID}" width="${MARK_WIDTH}" height="${MARK_HEIGHT}" alt=""
                   style="display:block;width:${MARK_WIDTH}px;height:${MARK_HEIGHT}px;border:0;outline:none;text-decoration:none;" />
            </td>
            <td style="vertical-align:middle;">
              <div style="font:700 27px/1.05 ${SANS};color:${BAND_HEADING};letter-spacing:-.02em;">${APP_NAME}</div>
              <div style="margin-top:5px;font:400 12px/1.2 ${SANS};color:${BAND_MUTED};letter-spacing:.13em;text-transform:uppercase;">${DIVISION_NAME}</div>
            </td>
          </tr></table>
        </td></tr>

        <!-- The gold rule, full bleed. -->
        <tr><td bgcolor="${GOLD}" style="background:${GOLD};height:3px;line-height:3px;font-size:0;">&nbsp;</td></tr>
        <!-- …and the tab hanging off it. A row of its own rather than a
             negative margin, which email clients do not honour. -->
        <tr><td align="center" style="font-size:0;line-height:0;">${img(NOTCH)}</td></tr>

        <tr><td style="padding:26px 46px 34px 46px;font:400 15px/1.62 ${SANS};color:${BODY};">
          ${body}
        </td></tr>

        <!-- The footer band sits INSIDE the card, per the reference design. -->
        <tr><td bgcolor="${FOOT_BG}" style="background:${FOOT_BG};padding:18px 46px;border-top:1px solid ${BORDER};">
          <table role="presentation" cellpadding="0" cellspacing="0" border="0"><tr>
            <td style="padding-right:12px;vertical-align:middle;">${img(MAIL)}</td>
            <td style="vertical-align:middle;font:400 12px/1.5 ${SANS};color:${MUTED};">
              If you were not expecting this, you may safely ignore this email.
            </td>
          </tr></table>
        </td></tr>
      </table>

      <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="max-width:620px;">
        <tr><td align="center" style="padding:16px 8px 0 8px;font:400 11px/1.5 ${SANS};color:${MUTED};">
          ${ORGANISATION_NAME} &middot; ${DIVISION_NAME}
        </td></tr>
      </table>
    </td></tr>
  </table>
</body></html>`;
}

/* --------------------------------------------------------------------------
 * The pieces the reference design is made of
 * ------------------------------------------------------------------------ */

/** The ringed icon disc, centred, that opens a message. */
const badge = (icon: EmailIcon): string =>
  `<table role="presentation" cellpadding="0" cellspacing="0" border="0" align="center" style="margin:0 auto 18px auto;">
    <tr><td align="center" style="font-size:0;line-height:0;">${img(icon)}</td></tr>
  </table>`;

/** The headline, centred, over a short gold divider. */
const headline = (text: string): string =>
  `<h1 style="margin:0 0 14px 0;font:700 24px/1.28 ${SANS};color:${INK};text-align:center;letter-spacing:-.02em;">${text}</h1>
   <table role="presentation" cellpadding="0" cellspacing="0" border="0" align="center" style="margin:0 auto 22px auto;">
     <tr><td bgcolor="${GOLD}" style="background:${GOLD};width:42px;height:2px;line-height:2px;font-size:0;">&nbsp;</td></tr>
   </table>`;

const para = (html: string): string =>
  `<p style="margin:0 0 14px 0;font:400 15px/1.62 ${SANS};color:${BODY};">${html}</p>`;

/** The gold-tinted "Role Assigned" strip. */
const chip = (label: string, value: string): string =>
  `<table role="presentation" cellpadding="0" cellspacing="0" border="0" style="margin:18px 0 20px 0;">
    <tr><td bgcolor="${CHIP_BG}" style="background:${CHIP_BG};border:1px solid ${CHIP_EDGE};border-radius:7px;padding:11px 16px;">
      <table role="presentation" cellpadding="0" cellspacing="0" border="0"><tr>
        <td style="padding-right:11px;vertical-align:middle;">${img(ROLE)}</td>
        <td style="vertical-align:middle;font:400 14px/1.35 ${SANS};color:${MUTED};">
          ${label}&nbsp; <strong style="color:${INK};font-weight:700;">${value}</strong>
        </td>
      </tr></table>
    </td></tr>
  </table>`;

/** The primary action, centred. */
const button = (href: string, label: string): string =>
  `<table role="presentation" cellpadding="0" cellspacing="0" border="0" align="center" style="margin:22px auto 24px auto;">
    <tr><td bgcolor="${BRAND}" style="background:${BRAND};border-radius:6px;border-bottom:2px solid ${BRAND_DEEP};">
      <a href="${href}" style="display:inline-block;padding:14px 36px;font:600 15px/1 ${SANS};color:#ffffff;text-decoration:none;">${label}</a>
    </td></tr>
  </table>`;

/** The pale security note, with a shield. */
const noteBox = (html: string): string =>
  `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin:0 0 22px 0;">
    <tr><td bgcolor="${PANEL}" style="background:${PANEL};border-radius:7px;padding:13px 16px;">
      <table role="presentation" cellpadding="0" cellspacing="0" border="0"><tr>
        <td style="padding-right:12px;vertical-align:top;">${img(SHIELD_NOTE)}</td>
        <td style="vertical-align:top;font:400 13px/1.55 ${SANS};color:${MUTED};">${html}</td>
      </tr></table>
    </td></tr>
  </table>`;

/** Hairline · shield · hairline. */
const shieldRule = (): string =>
  `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin:0 0 18px 0;">
    <tr>
      <td style="background:${HAIRLINE};height:1px;line-height:1px;font-size:0;">&nbsp;</td>
      <td width="34" align="center" style="font-size:0;line-height:0;padding:0 10px;">${img(SHIELD_RULE)}</td>
      <td style="background:${HAIRLINE};height:1px;line-height:1px;font-size:0;">&nbsp;</td>
    </tr>
  </table>`;

/** "Paste this instead" — every message with a button carries one. */
const fallback = (url: string): string =>
  `<p style="margin:0;font:400 13px/1.6 ${SANS};color:${MUTED};">
     If the button does not work, copy and paste this link into your browser:
   </p>
   <p style="margin:6px 0 0 0;font:400 13px/1.5 ${SANS};word-break:break-all;">
     <a href="${url}" style="color:${LINK};text-decoration:underline;">${url}</a>
   </p>`;

/** A code, big enough to read off a phone and copy without mistyping. */
const codeBlock = (code: string): string =>
  `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin:20px 0;">
    <tr><td align="center" bgcolor="${PANEL}" style="background:${PANEL};border:1px solid ${BORDER};border-radius:9px;padding:18px;">
      <div style="font:600 10px/1 ${SANS};color:${MUTED};letter-spacing:.12em;text-transform:uppercase;padding-bottom:9px;">Your code</div>
      <div style="font:700 31px/1 ${MONO};letter-spacing:.2em;color:${INK};">${code}</div>
    </td></tr>
  </table>`;

/* ==========================================================================
 * Invitation — FR-142
 * ========================================================================== */

export function invitationEmail(input: {
  fullName: string;
  invitedByName: string;
  roleLabel: string;
  activationUrl: string;
}): Email {
  const firstName = input.fullName.split(' ')[0];

  return {
    /* ⚠️ Not "X has set up your account" — in an inbox that reads as a
       notification about somebody else. This is addressed to the reader. */
    subject: `You're invited to join ${APP_NAME}`,
    html: shell(
      `${badge(INVITE_BADGE)}
       ${headline(`You&rsquo;re invited to join ${APP_NAME}`)}
       ${para(`Dear <strong style="color:${INK};">${firstName}</strong>,`)}
       ${para(
         `We are pleased to invite you to join <strong style="color:${INK};">${APP_NAME}</strong>, the task
          and operations platform for ${ORGANISATION_NAME}&rsquo;s ${DIVISION_NAME}.`,
       )}
       ${para(
         `Your account has been created so you can collaborate with the team, view assigned work,
          track progress, and manage project activity in one place.`,
       )}
       ${chip('Role Assigned:', input.roleLabel)}
       ${para('To activate your account and create your password, please use the invitation link below.')}
       ${button(input.activationUrl, 'Accept Invitation')}
       ${noteBox(
         `This invitation was sent by ${input.invitedByName}. For your security, only you can set
          your password. This link can be used once and
          <strong style="color:${INK};">expires in ${SYSTEM_DEFAULTS.activationTokenTtlHours} hours</strong>.`,
       )}
       ${shieldRule()}
       ${fallback(input.activationUrl)}`,
      `Accept your invitation and set up your sign-in.`,
    ),
    text: [
      `You're invited to join ${APP_NAME}`,
      ``,
      `Dear ${firstName},`,
      ``,
      `We are pleased to invite you to join ${APP_NAME}, the task and operations`,
      `platform for ${ORGANISATION_NAME}'s ${DIVISION_NAME}.`,
      ``,
      `Role assigned: ${input.roleLabel}`,
      ``,
      `To activate your account and create your password, use this link:`,
      input.activationUrl,
      ``,
      `Sent by ${input.invitedByName}. Only you can set your password. The link`,
      `works once and expires in ${SYSTEM_DEFAULTS.activationTokenTtlHours} hours.`,
    ].join('\n'),
    attachments: attach(INVITE_BADGE, ROLE, SHIELD_NOTE, SHIELD_RULE, MAIL),
  };
}

/* ==========================================================================
 * Password reset — FR-155
 * ========================================================================== */

export function passwordResetEmail(input: { fullName: string; code: string; resetUrl: string }): Email {
  const firstName = input.fullName.split(' ')[0];

  return {
    subject: `Your ${APP_NAME} password reset code`,
    html: shell(
      `${badge(KEY_BADGE)}
       ${headline('Reset your password')}
       ${para(`Dear <strong style="color:${INK};">${firstName}</strong>,`)}
       ${para('Somebody asked to reset the password on your account. Your code is below.')}
       ${codeBlock(input.code)}
       ${button(input.resetUrl, 'Reset My Password')}
       ${noteBox(
         `The code expires in <strong style="color:${INK};">${SYSTEM_DEFAULTS.recoveryCodeTtlMinutes} minutes</strong>
          and works once. Resetting signs you out everywhere, on every device.
          <br /><br /><strong style="color:${INK};">If this was not you</strong>, ignore this message — your
          password has not changed. Tell your administrator if it keeps happening.`,
       )}
       ${shieldRule()}
       ${fallback(input.resetUrl)}`,
      `Your reset code is ${input.code}. It expires in ${SYSTEM_DEFAULTS.recoveryCodeTtlMinutes} minutes.`,
    ),
    text: [
      `Dear ${firstName},`,
      ``,
      `Your ${APP_NAME} password reset code is: ${input.code}`,
      ``,
      input.resetUrl,
      ``,
      `It expires in ${SYSTEM_DEFAULTS.recoveryCodeTtlMinutes} minutes and works once.`,
      `Resetting signs you out on every device.`,
      ``,
      `If this was not you, ignore this message. Your password has not changed.`,
    ].join('\n'),
    attachments: attach(KEY_BADGE, SHIELD_NOTE, SHIELD_RULE, MAIL),
  };
}

/* ==========================================================================
 * Account unlock — FR-155a
 * ========================================================================== */

export function unlockEmail(input: {
  fullName: string;
  code: string;
  unlockUrl: string;
  /* Passed in, not imported. Both are editable settings (FR-057), and an email
     that states the wrong lock policy is worse than one that omits it — the
     recipient has no way to tell it is stale. */
  lockAfter: number;
  lockClearsAfterMinutes: number;
}): Email {
  const firstName = input.fullName.split(' ')[0];

  return {
    subject: `Your ${APP_NAME} account has been locked`,
    html: shell(
      `${badge(KEY_BADGE)}
       ${headline('Your account is locked')}
       ${para(`Dear <strong style="color:${INK};">${firstName}</strong>,`)}
       ${para(
         `Your account locked itself after ${input.lockAfter} failed sign-in attempts. Use the code
          below to unlock it — your password does not change.`,
       )}
       ${codeBlock(input.code)}
       ${button(input.unlockUrl, 'Unlock My Account')}
       ${noteBox(
         `The lock also clears on its own after
          <strong style="color:${INK};">${input.lockClearsAfterMinutes} minutes</strong>.
          <br /><br /><strong style="color:${INK};">If those attempts were not you</strong>, somebody is
          trying your password. Tell your administrator, and change it once you are back in.`,
       )}
       ${shieldRule()}
       ${fallback(input.unlockUrl)}`,
      `Unlock code: ${input.code}.`,
    ),
    text: [
      `Dear ${firstName},`,
      ``,
      `Your ${APP_NAME} account locked after ${input.lockAfter} failed sign-in attempts.`,
      ``,
      `Unlock code: ${input.code}`,
      input.unlockUrl,
      ``,
      `Your password does not change. The lock also clears on its own after ${input.lockClearsAfterMinutes} minutes.`,
      ``,
      `If those attempts were not you, somebody is trying your password. Tell your administrator.`,
    ].join('\n'),
    attachments: attach(KEY_BADGE, SHIELD_NOTE, SHIELD_RULE, MAIL),
  };
}

/* ==========================================================================
 * Login alert — FR-151
 * ========================================================================== */

export function loginAlertEmail(input: {
  fullName: string;
  when: Date;
  ip: string | null;
  country: string | null;
  userAgent: string | null;
  appUrl: string;
}): Email {
  const firstName = input.fullName.split(' ')[0];

  /* A raw user-agent string is unreadable and the interesting part is small:
     which browser, on what. Anything unparseable is reported honestly as
     "an unrecognised browser" rather than guessed at. */
  const ua = input.userAgent ?? '';
  const browser =
    /Edg\//.test(ua) ? 'Edge'
    : /OPR\//.test(ua) ? 'Opera'
    : /Chrome\//.test(ua) ? 'Chrome'
    : /Safari\//.test(ua) && !/Chrome/.test(ua) ? 'Safari'
    : /Firefox\//.test(ua) ? 'Firefox'
    : 'an unrecognised browser';
  const platform =
    /Windows/.test(ua) ? 'Windows'
    : /Android/.test(ua) ? 'Android'
    : /iPhone|iPad/.test(ua) ? 'iOS'
    : /Mac OS X/.test(ua) ? 'macOS'
    : /Linux/.test(ua) ? 'Linux'
    : 'an unknown device';

  const stamp = input.when.toLocaleString('en-GB', {
    dateStyle: 'full',
    timeStyle: 'short',
    timeZone: 'Asia/Karachi',
  });
  const where = [input.country, input.ip].filter(Boolean).join(' · ') || 'an unknown location';

  return {
    subject: `New sign-in to your ${APP_NAME} account`,
    html: shell(
      `${badge(KEY_BADGE)}
       ${headline('A new device signed in')}
       ${para(`Dear <strong style="color:${INK};">${firstName}</strong>,`)}
       ${para('Your account was signed into from a device we have not seen before.')}
       <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin:0 0 20px 0;">
         <tr><td bgcolor="${PANEL}" style="background:${PANEL};border:1px solid ${BORDER};border-radius:7px;padding:14px 16px;font:400 14px/1.75 ${SANS};color:${INK};">
           <strong>When</strong> &middot; ${stamp} (Karachi)<br />
           <strong>Where</strong> &middot; ${where}<br />
           <strong>What</strong> &middot; ${browser} on ${platform}
         </td></tr>
       </table>
       ${noteBox(
         `<strong style="color:${INK};">If this was you</strong>, nothing to do — you will not be told
          again for this device.
          <br /><br /><strong style="color:${INK};">If it was not</strong>, change your password now. That
          signs out every device immediately, including whoever this was.`,
       )}
       ${button(`${input.appUrl}/forgot-password`, 'Change My Password')}`,
      `Signed in from ${where}.`,
    ),
    text: [
      `Dear ${firstName},`,
      ``,
      `Your ${APP_NAME} account was signed into from a device we have not seen before.`,
      ``,
      `When:  ${stamp} (Karachi)`,
      `Where: ${where}`,
      `What:  ${browser} on ${platform}`,
      ``,
      `If this was you, nothing to do.`,
      `If it was not, change your password now — that signs out every device immediately.`,
      `${input.appUrl}/forgot-password`,
    ].join('\n'),
    attachments: attach(KEY_BADGE, SHIELD_NOTE, MAIL),
  };
}

/* ==========================================================================
 * The sign-in address was changed — sent to the OLD address
 * ==========================================================================
 * ── THIS IS THE ONLY CONTROL ON AN IMMEDIATE EMAIL CHANGE ────────────────────
 * The change applies at once (REDESIGN-PLAN §2), because confirming a link at
 * the new address needs a verified sending domain the owner had deferred. What
 * keeps that honest is this message: somebody who moves the account cannot do it
 * silently. Take it away and an attacker with a live session and a password
 * changes the sign-in identity with no trace the real owner would ever see.
 *
 * ── IT DOES NOT OFFER A RESET LINK, AND THAT IS NOT AN OVERSIGHT ─────────────
 * Every other alert here ends with "change your password". That advice is
 * useless and would be actively cruel: by the time this arrives, this address is
 * no longer attached to the account, so "forgot password" on it reaches nothing.
 * The only real remedy is a person, so the message names one.
 *
 * ── THE NEW ADDRESS IS MASKED ────────────────────────────────────────────────
 * Enough to recognise your own typo, not enough to hand an attacker's inbox to
 * whoever else reads this mailbox.
 */

export function emailChangedEmail(input: {
  fullName: string;
  newEmail: string;
  when: Date;
  isSuperAdmin: boolean;
  appUrl: string;
}): Email {
  const firstName = input.fullName.split(' ')[0];
  const masked = maskEmail(input.newEmail);

  const stamp = input.when.toLocaleString('en-GB', {
    dateStyle: 'full',
    timeStyle: 'short',
    timeZone: 'Asia/Karachi',
  });

  /* Who to shout at. The Super Admin has nobody above them — saying "contact
     your Super Admin" to the Super Admin would be a dead end, and the real
     answer for that account is direct database access (doc 16 §6). */
  const remedy = input.isSuperAdmin
    ? 'Contact whoever administers this deployment straight away. Restoring the Super Admin address needs direct database access — it cannot be undone from inside the application.'
    : 'Contact your Super Admin straight away and ask them to change it back. You cannot do it yourself from here, because this address no longer signs in.';

  const remedyText = input.isSuperAdmin
    ? 'Contact whoever administers this deployment straight away. Restoring the Super Admin address needs direct database access.'
    : 'Contact your Super Admin straight away and ask them to change it back.';

  return {
    subject: `The sign-in address on your ${APP_NAME} account was changed`,
    html: shell(
      `${badge(KEY_BADGE)}
       ${headline('Your sign-in address changed')}
       ${para(`Dear <strong style="color:${INK};">${firstName}</strong>,`)}
       ${para(
         `The email address used to sign in to your account was changed. This message is going to
          the <strong style="color:${INK};">old</strong> address — the one you are reading now.`,
       )}
       <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin:0 0 20px 0;">
         <tr><td bgcolor="${PANEL}" style="background:${PANEL};border:1px solid ${BORDER};border-radius:7px;padding:14px 16px;font:400 14px/1.75 ${SANS};color:${INK};">
           <strong>When</strong> &middot; ${stamp} (Karachi)<br />
           <strong>Changed to</strong> &middot; ${masked}
         </td></tr>
       </table>
       ${noteBox(
         `<strong style="color:${INK};">If this was you</strong>, nothing to do. Sign in with the new
          address from now on — this one no longer works.
          <br /><br /><strong style="color:${INK};">If it was not you</strong>, your account has been taken
          over. ${remedy}`,
       )}
       ${para(
         `<span style="font-size:13px;color:${MUTED};">The change is recorded in the security log with
          the time and the address it came from, so there is a trail either way.</span>`,
       )}`,
      `Your sign-in address was changed to ${masked}.`,
    ),
    text: [
      `Dear ${firstName},`,
      ``,
      `The email address used to sign in to your ${APP_NAME} account was changed.`,
      `This message is going to the OLD address — the one you are reading now.`,
      ``,
      `When:       ${stamp} (Karachi)`,
      `Changed to: ${masked}`,
      ``,
      `If this was you, nothing to do. Sign in with the new address from now on —`,
      `this one no longer works.`,
      ``,
      `If it was not you, your account has been taken over. ${remedyText}`,
      ``,
      `The change is recorded in the security log either way.`,
      ``,
      input.appUrl,
    ].join('\n'),
    attachments: attach(KEY_BADGE, SHIELD_NOTE, MAIL),
  };
}

/* ==========================================================================
 * Welcome, after activation
 * ========================================================================== */

export function welcomeEmail(input: { fullName: string; appUrl: string; roleLabel: string }): Email {
  const firstName = input.fullName.split(' ')[0];

  return {
    subject: `You are set up on ${APP_NAME}`,
    html: shell(
      `${badge(INVITE_BADGE)}
       ${headline(`Welcome to ${APP_NAME}`)}
       ${para(`Dear <strong style="color:${INK};">${firstName}</strong>,`)}
       ${para(`Your account is active and your password is set. Welcome to the ${DIVISION_NAME}.`)}
       ${chip('Signed in as:', input.roleLabel)}
       <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin:0 0 4px 0;">
         <tr><td bgcolor="${PANEL}" style="background:${PANEL};border:1px solid ${BORDER};border-radius:7px;padding:14px 16px;font:400 14px/1.7 ${SANS};color:${BODY};">
           <strong style="color:${INK};">My Work</strong> is your queue and your capacity for the week.<br />
           Every task carries an estimate — that is what stops anyone being quietly overloaded.<br />
           If work is stuck, move it to <strong style="color:${INK};">Blocked</strong> and say why.
         </td></tr>
       </table>
       ${button(input.appUrl, `Open ${APP_NAME}`)}`,
      `Your account is ready.`,
    ),
    text: [
      `Dear ${firstName},`,
      ``,
      `Your ${APP_NAME} account is active. You are set up as ${input.roleLabel}.`,
      ``,
      `My Work is your queue and your capacity for the week.`,
      `Every task carries an estimate — that is what stops anyone being quietly overloaded.`,
      `If work is stuck, move it to Blocked and say why.`,
      ``,
      input.appUrl,
    ].join('\n'),
    attachments: attach(INVITE_BADGE, ROLE, MAIL),
  };
}

/* --------------------------------------------------------------------------
 * ATTENDANCE — owner instruction, 2026-08-25
 * ------------------------------------------------------------------------
 * Two messages, and both are reminders rather than reprimands.
 *
 * ⚠️ NEITHER OF THEM TELLS ANYBODY OFF. The owner asked for a nudge — *"send a
 * reminder and auto-send mail to them: 'You didn't check out today'"* — and a
 * system that scolds people about a button gets its mail filtered within a week,
 * at which point it reminds nobody of anything. Both say what was recorded, what
 * to do, and stop.
 * ---------------------------------------------------------------------- */

export function missedCheckoutEmail(input: {
  fullName: string;
  /** The day, already written out — see lib/now.ts on formatting. */
  dayLabel: string;
  checkedInLabel: string;
  appUrl: string;
}): Email {
  const firstName = input.fullName.split(' ')[0];

  return {
    subject: `You did not check out on ${input.dayLabel}`,
    html: shell(
      `${badge(SHIELD_NOTE)}
       ${headline('Your day is still open')}
       ${para(`Dear <strong style="color:${INK};">${firstName}</strong>,`)}
       ${para(
         `You checked in on <strong style="color:${INK};">${input.dayLabel}</strong> and the day was
          never closed, so no hours are recorded against it.`,
       )}
       ${chip('Checked in at:', input.checkedInLabel)}
       <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin:0 0 4px 0;">
         <tr><td bgcolor="${PANEL}" style="background:${PANEL};border:1px solid ${BORDER};border-radius:7px;padding:14px 16px;font:400 14px/1.7 ${SANS};color:${BODY};">
           If you have already left, an <strong style="color:${INK};">Admin</strong> can set the time you
           actually went — nobody else can, so ask rather than trying to fix it yourself.<br />
           If you are still working, the button is in the top bar whenever you finish.
         </td></tr>
       </table>
       ${button(`${input.appUrl}/attendance`, 'Open Attendance')}`,
      `You checked in on ${input.dayLabel} but never checked out.`,
    ),
    text: [
      `Dear ${firstName},`,
      '',
      `You checked in on ${input.dayLabel} at ${input.checkedInLabel} and never checked out, so no`,
      'hours are recorded against that day.',
      '',
      'If you have already left, ask an Admin to set the time you actually went.',
      'If you are still working, the check-out button is in the top bar.',
      '',
      `${input.appUrl}/attendance`,
    ].join('\n'),
    attachments: attach(SHIELD_NOTE, MAIL),
  };
}

export function lateArrivalsEmail(input: {
  fullName: string;
  lateCount: number;
  monthLabel: string;
  /** The rule, stated rather than implied — 10:30 today, editable tomorrow. */
  lateAfterLabel: string;
  appUrl: string;
}): Email {
  const firstName = input.fullName.split(' ')[0];
  /* ⚠️ "third time" is what the owner asked to say, but the number is whatever it
     actually is: a message claiming "third" to somebody on their fifth is a message
     they stop believing. */
  const ordinal =
    input.lateCount === 3 ? 'third' : input.lateCount === 4 ? 'fourth' : `${input.lateCount}th`;

  return {
    subject: `You have arrived late ${input.lateCount} times in ${input.monthLabel}`,
    html: shell(
      `${badge(SHIELD_RULE)}
       ${headline('A note about your arrival time')}
       ${para(`Dear <strong style="color:${INK};">${firstName}</strong>,`)}
       ${para(
         `This is the <strong style="color:${INK};">${ordinal}</strong> late arrival recorded against
          you in ${input.monthLabel}.`,
       )}
       ${chip('Counted as late after:', input.lateAfterLabel)}
       <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin:0 0 4px 0;">
         <tr><td bgcolor="${PANEL}" style="background:${PANEL};border:1px solid ${BORDER};border-radius:7px;padding:14px 16px;font:400 14px/1.7 ${SANS};color:${BODY};">
           The count resets on the first of each month. You can see every day of it on your
           attendance page, including the exact times.<br />
           If a time is wrong, an <strong style="color:${INK};">Admin</strong> can correct it.
         </td></tr>
       </table>
       ${button(`${input.appUrl}/attendance`, 'See your attendance')}`,
      `${input.lateCount} late arrivals recorded in ${input.monthLabel}.`,
    ),
    text: [
      `Dear ${firstName},`,
      '',
      `This is the ${ordinal} late arrival recorded against you in ${input.monthLabel}.`,
      `Anything after ${input.lateAfterLabel} counts as late. The count resets on the 1st.`,
      '',
      'You can see every day of it, with the exact times, on your attendance page.',
      'If a time is wrong, an Admin can correct it.',
      '',
      `${input.appUrl}/attendance`,
    ].join('\n'),
    attachments: attach(SHIELD_RULE, MAIL),
  };
}

/* ==========================================================================
 * Invoice — owner request 2026-08-29
 * ==========================================================================
 * *"With the proper email template — right now we are using an email template,
 * follow that template also, in which the PDF will be attached."*
 *
 * So this is the same shell, the same band, the same gold rule and the same
 * `cid:` PNG icons as every other message. Nothing new was designed for it.
 *
 * ── ⚠️ THE ONE MESSAGE IN THIS FILE THAT GOES OUTSIDE THE COMPANY ──────────
 * Every other template addresses a colleague who has an account. This one goes
 * to a client, and three things follow from that:
 *
 *   1. NO LINK INTO THE APPLICATION. Every other message ends in a button to a
 *      page; a client has no account and a sign-in screen is a dead end that
 *      reads as a broken invoice. The PDF is the payload, so the message's job
 *      is to say what it is and get out of the way.
 *   2. NOTHING INTERNAL LEAKS. No project code, no note, no who-recorded-it.
 *      The client note is passed separately and deliberately — `note` on the
 *      row is internal and never reaches here.
 *   3. EVERY INTERPOLATED VALUE IS ESCAPED. See `esc` below.
 *
 * ── ⚠️ THE AMOUNT AND THE DUE DATE ARE IN THE BODY, NOT ONLY IN THE PDF ────
 * A client reading on a phone will not open an attachment to find out what they
 * owe and by when. Those two facts are the message; the PDF is the record.
 */

/**
 * ⚠️ HTML-ESCAPED, unlike every other interpolation in this file, and the
 * difference is not inconsistency.
 *
 * Elsewhere the values are a colleague's own name and a role label — data this
 * system generated. Here they are a client name and address typed by an Admin
 * into a form, and the output is sent to a third party. An `&` in "Smith & Co"
 * renders as a broken entity without this; an angle bracket would put whatever
 * follows it into the markup. Neither is a likely attack and both are a badly
 * rendered invoice, which is enough.
 */
const esc = (value: string): string =>
  value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');

export function invoiceEmail(input: {
  /** Who it is addressed to — the contact person, or the company. */
  greetingName: string;
  invoiceNo: string;
  /** Already formatted, e.g. `PKR 139,200`. See lib/domain/money.ts. */
  amountLabel: string;
  /** Already written out, e.g. `11 Sep 2026` — the server formats dates. */
  dueDateLabel: string;
  issuedDateLabel: string;
  /** "Monthly invoice", "Project add-on invoice"… */
  kindLabel: string;
  /** What it is for, in one line — the first invoice line's description. */
  forWhat: string;
  companyName: string;
  /** The Admin's own note to the client, or null. Never the internal note. */
  clientNote: string | null;
  /** How to reach a person about it. Omitted when the company has no address set. */
  replyTo: string | null;
  /** True on a second or later send, so the client is told rather than confused. */
  isResend: boolean;
}): Email {
  const firstName = esc(input.greetingName.split(' ')[0] || input.greetingName);

  return {
    /* ⚠️ The number is IN THE SUBJECT. It is how a client's accounts department
       files it, how they search for it six weeks later, and how a reply gets
       matched back to it. */
    subject: input.isResend
      ? `Reminder: invoice ${input.invoiceNo} from ${input.companyName}`
      : `Invoice ${input.invoiceNo} from ${input.companyName}`,

    html: shell(
      `${badge(INVITE_BADGE)}
       ${headline(input.isResend ? 'A reminder of your invoice' : 'Your invoice is attached')}
       ${para(`Dear <strong style="color:${INK};">${firstName}</strong>,`)}
       ${para(
         input.isResend
           ? `This is a reminder of invoice <strong style="color:${INK};">${esc(input.invoiceNo)}</strong>,
              issued on ${esc(input.issuedDateLabel)}. The original is attached again below.`
           : `Please find invoice <strong style="color:${INK};">${esc(input.invoiceNo)}</strong> attached,
              covering ${esc(input.forWhat)}.`,
       )}

       <!-- ⚠️ THE TWO FACTS A CLIENT ACTUALLY NEEDS, before any attachment is
            opened: what is owed, and by when. Laid out as a table because
            flexbox is unreliable in mail clients, and painted with both a
            bgcolor attribute and a CSS background so the panel survives a
            client that strips one of them. -->
       <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin:20px 0 18px 0;">
         <tr>
           <td bgcolor="${PANEL}" style="background:${PANEL};border:1px solid ${BORDER};border-radius:9px;padding:18px 20px;">
             <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0">
               <tr>
                 <td style="font:600 10px/1 ${SANS};color:${MUTED};letter-spacing:.1em;text-transform:uppercase;padding-bottom:7px;">
                   Amount due
                 </td>
                 <td align="right" style="font:600 10px/1 ${SANS};color:${MUTED};letter-spacing:.1em;text-transform:uppercase;padding-bottom:7px;">
                   Due by
                 </td>
               </tr>
               <tr>
                 <td style="font:700 22px/1.15 ${SANS};color:${BRAND};">${esc(input.amountLabel)}</td>
                 <td align="right" style="font:700 15px/1.15 ${SANS};color:${INK};">${esc(input.dueDateLabel)}</td>
               </tr>
             </table>
           </td>
         </tr>
       </table>

       ${chip('Invoice type:', esc(input.kindLabel))}

       ${
         input.clientNote
           ? `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin:0 0 18px 0;">
                <tr><td bgcolor="${PANEL}" style="background:${PANEL};border:1px solid ${BORDER};border-radius:7px;padding:14px 16px;font:400 14px/1.7 ${SANS};color:${BODY};">
                  ${esc(input.clientNote)}
                </td></tr>
              </table>`
           : ''
       }

       ${para(
         `The full invoice, with the payment details, is attached as a PDF.${
           input.replyTo
             ? ` If anything looks wrong, reply to this message or write to
                 <a href="mailto:${esc(input.replyTo)}" style="color:${LINK};text-decoration:underline;">${esc(input.replyTo)}</a>.`
             : ' If anything looks wrong, reply to this message.'
         }`,
       )}

       ${shieldRule()}

       <!-- ⚠️ NO BUTTON INTO THE APPLICATION. A client has no account here, and
            a link to a sign-in screen on an invoice reads as a broken document.
            Every other template in this file ends in one; this is the exception,
            on purpose. -->
       <p style="margin:0;font:400 13px/1.6 ${SANS};color:${MUTED};">
         ${esc(input.companyName)} &middot; Invoice ${esc(input.invoiceNo)}
       </p>`,
      /* The inbox preview line. The amount and the date again, because for many
         readers this is the only part they will see before deciding to open it. */
      `${esc(input.amountLabel)} due by ${esc(input.dueDateLabel)}. Invoice ${esc(input.invoiceNo)} is attached.`,
    ),

    text: [
      `Dear ${input.greetingName.split(' ')[0] || input.greetingName},`,
      '',
      input.isResend
        ? `This is a reminder of invoice ${input.invoiceNo}, issued on ${input.issuedDateLabel}.`
        : `Please find invoice ${input.invoiceNo} attached, covering ${input.forWhat}.`,
      '',
      `Amount due:  ${input.amountLabel}`,
      `Due by:      ${input.dueDateLabel}`,
      `Type:        ${input.kindLabel}`,
      ...(input.clientNote ? ['', input.clientNote] : []),
      '',
      'The full invoice, with the payment details, is attached as a PDF.',
      input.replyTo
        ? `If anything looks wrong, reply to this message or write to ${input.replyTo}.`
        : 'If anything looks wrong, reply to this message.',
      '',
      `${input.companyName} · Invoice ${input.invoiceNo}`,
    ].join('\n'),

    /* ⚠️ The PDF is NOT in here. These are the inline `cid:` images the shell
       references; the document is appended by the caller, with no content id, so
       it arrives as a paperclip rather than as hidden inline content. See the
       note on `sendEmail`'s `attachments`. */
    attachments: attach(INVITE_BADGE, ROLE, SHIELD_RULE, MAIL),
  };
}
