/* ============================================================================
 * THE OPERATIONS SCORE
 * ----------------------------------------------------------------------------
 * The owner's "Holographic Control Room" reference carries an "AI Productivity
 * Score — 87/100". This product has no model scoring anything, so the choice
 * was between a constant that looks like a measurement and a real measurement
 * that fills the same slot. This is the second.
 *
 * ── ⚠️ WHAT IT IS, STATED PLAINLY ───────────────────────────────────────────
 * A weighted blend of three things the database can actually answer:
 *
 *   delivery   50%  what share of settled work was finished rather than left
 *                   late — the closest thing to "are we shipping"
 *   capacity   30%  how close the team is to the healthy band; punished for
 *                   being over AND for being idle, because both are a planning
 *                   failure
 *   punctuality 20% what share of expected people were in on time today
 *
 * ── ⚠️ AND WHAT IT IS NOT ───────────────────────────────────────────────────
 * It is NOT a productivity measurement of any individual, and nothing here is
 * per-person. A score that ranked people would be read as a performance review
 * generated by a machine, which is precisely the thing an "AI score" must never
 * quietly become.
 *
 * ⚠️ A missing input is EXCLUDED, not counted as zero. A division with no
 * attendance recorded yet should score on delivery and capacity alone — scoring
 * their punctuality as 0/20 would report a crisis that is really an empty table.
 * ========================================================================= */

export interface OpsInputs {
  /** Tasks completed in the window. */
  readonly completed: number;
  /** Tasks currently overdue. */
  readonly overdue: number;
  /** Tasks currently open. */
  readonly open: number;
  /** Team utilisation, 0–100+. */
  readonly utilisationPct: number;
  /** The band the division aims to sit under, from settings. */
  readonly softThresholdPct: number;
  /** People expected in today. Zero means "no attendance data" — see above. */
  readonly expectedToday: number;
  /** Of those, how many were in on time (not late). */
  readonly onTimeToday: number;
}

export interface OpsScore {
  readonly score: number;
  readonly headline: string;
  readonly parts: {
    readonly delivery: number | null;
    readonly capacity: number | null;
    readonly punctuality: number | null;
  };
}

/** Clamp to 0–100 and round. Every part below is a percentage. */
const pct = (n: number): number => Math.max(0, Math.min(100, Math.round(n)));

export function operationsScore(input: OpsInputs): OpsScore {
  /* ── Delivery ────────────────────────────────────────────────────────────
     Finished work against finished-plus-late. Null when nothing has been
     completed AND nothing is late: a brand-new division has no delivery record,
     which is not the same as a bad one. */
  const settled = input.completed + input.overdue;
  const delivery = settled === 0 ? null : pct((input.completed / settled) * 100);

  /* ── Capacity ────────────────────────────────────────────────────────────
     ⚠️ Two-sided. 100% is not the target — the target is the healthy band
     BELOW the soft threshold, so a team at 40% of capacity is not "better" than
     one at 75%; it is under-loaded, and the plan is wrong either way. Full
     marks inside the band, falling off on both sides. */
  const target = Math.max(1, input.softThresholdPct);
  const capacity =
    input.utilisationPct <= 0
      ? null
      : input.utilisationPct > target
        ? /* Over: every point above the threshold costs two, so 100% against a
             threshold of 85 lands at 70. */
          pct(100 - (input.utilisationPct - target) * 2)
        : /* Under: scaled up to the threshold, with a floor of 55 so a quiet
             week is a nudge rather than an alarm. */
          pct(55 + (input.utilisationPct / target) * 45);

  /* ── Punctuality ─────────────────────────────────────────────────────────
     Null when nobody was expected — a Sunday, or a division with no attendance
     rows yet. */
  const punctuality =
    input.expectedToday <= 0 ? null : pct((input.onTimeToday / input.expectedToday) * 100);

  /* ── The blend ───────────────────────────────────────────────────────────
     ⚠️ Re-normalised over the parts that EXIST, so dropping an input shifts the
     weight onto the others rather than dragging the total down. */
  const weighted: Array<[number, number]> = [];
  if (delivery !== null) weighted.push([delivery, 0.5]);
  if (capacity !== null) weighted.push([capacity, 0.3]);
  if (punctuality !== null) weighted.push([punctuality, 0.2]);

  const totalWeight = weighted.reduce((sum, [, w]) => sum + w, 0);
  const score =
    totalWeight === 0
      ? 0
      : pct(weighted.reduce((sum, [value, w]) => sum + value * w, 0) / totalWeight);

  return { score, headline: headlineFor(score, totalWeight === 0), parts: { delivery, capacity, punctuality } };
}

function headlineFor(score: number, empty: boolean): string {
  if (empty) return 'Not enough recorded yet to score.';
  if (score >= 85) return 'Delivery, capacity and attendance are all healthy.';
  if (score >= 70) return 'Broadly on track, with one area worth a look.';
  if (score >= 50) return 'Slipping in at least one area — see below.';
  return 'Several areas need attention today.';
}

/**
 * The recommendations under the score.
 *
 * ⚠️ Ordered by cost of ignoring, and CAPPED at three. The panel is small and a
 * list of eight suggestions is a list nobody acts on — the same reasoning as the
 * dashboard's "needs a decision" cap.
 */
export function operationsAdvice(
  input: OpsInputs & { atRisk: number; blocked: number; pendingExtensions: number },
): string[] {
  const out: string[] = [];

  if (input.blocked > 0) {
    out.push(
      `${input.blocked} ${input.blocked === 1 ? 'task is' : 'tasks are'} blocked — that work is stopped until somebody clears it.`,
    );
  }
  if (input.overdue > 0) {
    out.push(
      `${input.overdue} ${input.overdue === 1 ? 'task is' : 'tasks are'} overdue. Re-plan or re-assign before adding new work.`,
    );
  }
  if (input.atRisk > 0) {
    out.push(
      `${input.atRisk} ${input.atRisk === 1 ? 'person is' : 'people are'} at or near their capacity limit — rebalance before assigning more.`,
    );
  }
  if (input.pendingExtensions > 0) {
    out.push(
      `${input.pendingExtensions} extension ${input.pendingExtensions === 1 ? 'request is' : 'requests are'} waiting on a decision.`,
    );
  }
  if (input.utilisationPct > 0 && input.utilisationPct < input.softThresholdPct * 0.5) {
    out.push('The team is well under capacity this week — there is room to pull work forward.');
  }

  return out.slice(0, 3);
}
