-- =============================================================================
-- 039 · A REPORT KEEPS ITS CONTENT, NOT JUST A PICTURE OF IT
-- -----------------------------------------------------------------------------
-- Owner, 2026-08-20, having supplied four reference layouts and six illustration
-- assets: *"Now design, because the purpose of giving all these things is that I want
-- the same presentation."*
--
-- ── ⚠️ WHY THIS MIGRATION EXISTS ─────────────────────────────────────────────
-- Migration 038 stored a generated PNG and assumed a report WAS that PNG. Measured
-- afterwards: `gpt-image-1` reproduced the figures correctly (32 / 27 / 5 / 21 / 6 /
-- 84% / 61 all right) but garbled the WORDS — the project name came back as "NAYA
-- MARKITING", a heading as "RERIIMED", the date as 2025 when 2026 was sent, and the
-- division's logo redrawn rather than reproduced. A document with the client's own name
-- misspelled cannot be sent, so the same layout is now DRAWN by
-- `lib/pdf/report-poster.ts` from the owner's assets, with real type.
--
-- That changes what a report row has to remember. A drawn page is rebuilt from its
-- CONTENT, so the content is what is stored — and the PDF becomes a pure function of it.
--
-- ── ⚠️ WHY STORE THE CONTENT RATHER THAN RE-QUERY IT ──────────────────────────
-- A report is a statement about a period that has closed. Re-deriving it later would
-- produce a DIFFERENT document as tasks are edited, back-dated or completed — so
-- "which figures did we send the client in August?" would have no answer. The stored
-- blob is the answer. It is also what makes the PDF free and instant to rebuild.
--
-- ── image_path BECOMES NULLABLE, AND THAT IS THE POINT ────────────────────────
-- A drawn report has no stored image. The old rows keep theirs and still render through
-- the image branch of the PDF route, so nothing already generated breaks. The check
-- constraint below is what stops a row that has NEITHER — which would be a report that
-- cannot be rendered at all.
-- =============================================================================

alter table public.project_reports
  add column if not exists content jsonb;

comment on column public.project_reports.content is
  'The full ReportContent this report was built from (lib/domain/report-content.ts). '
  'Null on rows generated by the image model before migration 039.';

-- A drawn report has no image. ⚠️ Dropped rather than defaulted to '': a blank path
-- would pass the not-blank check on 038 and then 404 at render time.
alter table public.project_reports
  alter column image_path drop not null;

-- ⚠️ 038's check fires on NULL as unknown, which passes — so it does not need dropping
-- for null paths to be accepted. Re-created anyway to say so explicitly: a path that is
-- present must not be blank.
alter table public.project_reports
  drop constraint if exists project_reports_image_path_not_blank;
alter table public.project_reports
  add constraint project_reports_image_path_not_blank
  check (image_path is null or length(btrim(image_path)) > 0);

-- ⚠️ THE ONE THAT MATTERS: every row must be renderable by one route or the other.
alter table public.project_reports
  drop constraint if exists project_reports_renderable;
alter table public.project_reports
  add constraint project_reports_renderable
  check (content is not null or image_path is not null);

-- `summary` was 'the exact text given to the image model'. For a drawn report it is the
-- human-readable digest of the same figures, kept for the same reason: a row that can be
-- read without a PDF renderer.
comment on column public.project_reports.summary is
  'A human-readable digest of the report. For image-model rows, the exact prompt text '
  'the model was given. Append-only — see the note on UPDATE in migration 038.';

-- =============================================================================
-- SELF-CHECK
-- -----------------------------------------------------------------------------
-- ⚠️ Runs as `cni_app`. A check running as `postgres` bypasses table GRANTs and proves
-- nothing about them — `/documents` shipped broken exactly that way.
-- =============================================================================
do $$
declare
  v_admin   uuid;
  v_project uuid;
  v_report  uuid;
  n         integer;
begin
  select id into v_admin from public.users
   where role in ('admin', 'super_admin') and is_active order by role limit 1;

  if v_admin is null then
    raise notice '039 · no admin yet, skipping the row-level self-check';
    return;
  end if;

  insert into public.projects (name, code, type, status, created_by_id, owner_id)
  values ('039 report content check', 'OTH', 'other', 'planning', v_admin, v_admin)
  returning id into v_project;

  set local role cni_app;
  perform set_config('app.user_id', v_admin::text, true);

  -- ── A DRAWN report: content, no image ─────────────────────────────────────
  insert into public.project_reports
    (project_id, kind, period_start, period_end, period_label,
     content, summary, model, created_by_id)
  values (v_project, 'week', '2026-08-17', '2026-08-23', '17 Aug - 23 Aug 2026',
          '{"kind":"week","projectName":"039 check","activityTotal":"5"}'::jsonb,
          'A digest', 'cni-composer', v_admin)
  returning id into v_report;

  select count(*) into n from public.project_reports
   where id = v_report and image_path is null and content is not null;
  if n <> 1 then raise exception '039 · a drawn report could not be stored without an image'; end if;

  -- ── An IMAGE report still works, unchanged ────────────────────────────────
  insert into public.project_reports
    (project_id, kind, period_start, period_end, period_label,
     image_path, summary, model, created_by_id)
  values (v_project, 'month', '2026-08-01', '2026-08-31', 'August 2026',
          'project-reports/x.png', 'A summary', 'gpt-image-1', v_admin);

  -- ── ⚠️ NEITHER is refused. This is the constraint that stops an unrenderable row.
  begin
    insert into public.project_reports
      (project_id, kind, period_start, period_end, period_label,
       summary, model, created_by_id)
    values (v_project, 'today', current_date, current_date, 'Today',
            'A summary', 'cni-composer', v_admin);
    raise exception '039 · a report with neither content nor an image was accepted';
  exception when check_violation then null;
  end;

  -- ── A blank path is still refused ─────────────────────────────────────────
  begin
    insert into public.project_reports
      (project_id, kind, period_start, period_end, period_label,
       image_path, summary, model, created_by_id)
    values (v_project, 'today', current_date, current_date, 'Today',
            '   ', 'A summary', 'gpt-image-1', v_admin);
    raise exception '039 · a blank image path was accepted';
  exception when check_violation then null;
  end;

  -- ── ⚠️ STILL append-only. The content must not be rewritable either, or the
  --    stored figures stop being evidence of what was sent.
  begin
    update public.project_reports set content = '{}'::jsonb where id = v_report;
    raise exception '039 · a stored report content was rewritten';
  exception when insufficient_privilege then null;
  end;

  reset role;
  delete from public.project_reports where project_id = v_project;
  delete from public.projects where id = v_project;

  raise notice '039 · drawn reports store their content, image rows still work, both stay append-only';
end
$$;
